### ISSUE TITLE
README gives no/poor guidance for MFA

### ISSUE THREAD

**Issue by jcollum-nike** [Nike-Inc/gimme-aws-creds#124]
```
✗ gimme-aws-creds --version
gimme-aws-creds 1.1.8
✗ gimme-aws-creds
No device token in configuration.  Try running --register_device again.
✗ gimme-aws-creds --register_device
Using password from keyring for justin.collum@nike.com
Multi-factor Authentication required.
Pick a factor:
Selection: 
```

Uhh, now what? I selected SMS in config: 

```
If you'd like to set a preferred device type to use for MFA, enter it here.
This is optional. valid devices types:[sms, call, push, token, token:software:totp]
Preferred MFA Device Type [token]: sms
Do you want the MFA device be remembered?
Please answer y or n.
Remember device [n]: y
```

I have Google Authenticator set as my MFA token gen. I don't know which of those options to choose in this case.

**Comment by JonGilmore** [comment]
I've seen this same behavior - if you select a default MFA device type that you don't have active on your Okta account, it'll show no options because there are no options to show. In your case, you should leave the `preferred_mfa_type` to empty, then it'll prompt you with the available types on your account.
