### ISSUE TITLE
Appears to login but AWS CLI and Boto3 won't work

### ISSUE THREAD

**Issue by HalinGG** [Nike-Inc/gimme-aws-creds#161]
Hi, gimme-aws-creds appears to sign me into the correct role:

........
........
Saving arn:aws:iam::xxx123456xxx:role/MyAccountAdministrator as xxx123456xxx-MyAccountAdministrator
Written profile xxx123456xxx-MyAccountAdministrator to /Users/halingg/.aws/credentials

... But I get errors with Aws-Cli and Boto3:

botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetRestApis operation: User: arn:aws:sts::xxx123456xxx:assumed-role/MyAccountAdministrator/halingg is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-east-2::/restapis

In my config I'm using:

gimme_creds_server = appurl

In the credentials file, it's writing the profile with access keys and all but when I use the profile, I get the errors above.

Any advice on debugging this? I feel stuck.

Thank you,

Halin

**Comment by JDTAY** [comment]
Are you using MacOS Catalina by any chance?

Have a look at your homedir and see if you find a ~ (tilde) directory. E.g. do you see this in your terminal?

/Users/Halin/~

I found the same problem. Basically gimme-aws-creds was writing my credentials to /Users/Me/~/.aws/credentials instead of to /Users/Me/.aws/credentials so the profile keys didn't exist. 

It went away after performing a clean wipe of my MacBook. 

The issue isn't specifically to do with gimme-aws-creds btw, I never really got to the bottom of it. Both Python3 and GoLang performed the same natively when calling ~ from my code or a terminal. 

--
 Jonathon Taylor
 jonathon@jdtay.com

**Comment by HalinGG** [comment]
Thanks @JDTAY ! It had to do with the credentials file mapping like you said.
