### ISSUE TITLE
Improve SAML response error output

### ISSUE THREAD

**Issue by crashGoBoom** [Nike-Inc/gimme-aws-creds#195]
Hello! Currently the only output we see when a SAML request returns something unexpected is:
`Did not receive SAML Response after successful authentication [' + url + ']'`

But a reason for the error would be useful if one is located in the response.

PR Incoming. 😄 

## Expected Behavior
It should output the reason for not containing the SAML provided in the response text.

## Possible Solution
Parse the response and output the error if provided.

## Context
This would prove useful for users troubleshooting cli commands such as Issues #182 #151 #137

**Comment by elijah-roberts** [comment]
@Sector95  I agree this would be helpful, just had someone today wanting to know what the issue was. Turned out that we had a vpn restriction and they were not signed in. A more helpful error message would help alleviate administration.

@crashGoBoom I was actually logging on to create an issue for this, and a PR myself. I notice there are no added tests, that said this is a pretty simple change with a failback if no error message is found. Do you possibly have an example of returned error messages. I.E VPN Sign on policy, Mobile restriction Sign on policy, etc...

**Comment by gadupushailaja** [comment]
@crashGoBoom In our case, SAML response is different and the if condition which is checking for Extra Verification string does not exists in title and SAML response does not contain session token. I have to add a separate condition to make it work and it looks good so far.
More information in the following link.
https://github.com/Nike-Inc/gimme-aws-creds/issues/182#issuecomment-624690652

**Comment by crashGoBoom** [comment]
@elijah-roberts Hi! Sorry I dont have the error output but perhaps we can get the response from someone else who has saved it?

**Comment by crashGoBoom** [comment]
https://github.com/Nike-Inc/gimme-aws-creds/pull/196 was merged in so this can be closed.
