### ISSUE TITLE
Unable to run on windows 10 does not even return error

### ISSUE THREAD

**Issue by frankscalzo** [Nike-Inc/gimme-aws-creds#197]
i have this installed successfully on my mac and on a Linux machine i try to install on Win10 and it installs but if i try to run it in a cmd window it returns a blank line and back to cursor on CMD even if i try to configure or help or version. maybe im doing something  wrong?

**Comment by elijah-roberts** [comment]
I had a co-worker run into this recently, and they ended up doing a full reinstall of python and that fixed it for them... Be sure to install all the dev packages, and for all users...

**Comment by iniquityx2** [comment]
I'm having the same issue.  I recently ran a pip install and upgraded from an old version that did not have this issue.

**Comment by SecurityGorilla** [comment]
I have the same issue. It worked a few months ago, installed on a different machine and can't run it in Windows 10.

**Comment by frankscalzo** [comment]
I tried to do the reinstall of Python and still no luck i even saw another thread on changing Fido and still no luck

Issue 190

**Comment by iniquityx2** [comment]
Based on the details in https://github.com/Nike-Inc/gimme-aws-creds/issues/188 i reverted to a prior version and was fine.  

Per curtis-turners input i ran pip install gimme-aws-creds==2.3.1 and have been good.

There are some other suggestions there too but haven't gotten around to them since i'm good at the moment with the older working version

**Comment by frankscalzo** [comment]
@iniquityx2 you rock thanks for the catch that did the trick

**Comment by frankscalzo** [comment]
based on suggested Fix closing this
