### ISSUE TITLE
Okta is using another IdP for user authentication and gimme-aws-creds does not force user assertion.

### ISSUE THREAD

**Issue by ghost** [Nike-Inc/gimme-aws-creds#353]
We use Okta as our directory and application SSO and gimme-aws-creds to access account roles. However, we are switching systems and are authenticating to Okta using our corporate directory. So, when we try to login to Okta, we get redirected to another IdP, enter a second factor, and then allowed to access Okta and our apps. Now, with this new setup and trying to use gimme-aws-creds, all I am asked for is my Okta password and it gives me AWS CLI access. I am not redirected to my IdP to confirm my identity (and use MFA). This is not ideal as it allows for username/password access to the AWS CLI and bypasses our IdP.

## Expected Behavior
When using gimme-aws-creds, after entering user password, I am redirected to the IdP that asserts our Okta users. Once I have confirmed my identity including MFA, I am allowed access to the AWS CLI. Otherwise, I should not get access.

## Current Behavior
I use gimme-aws-creds, it asks for my Okta password, then it allows me access to AWS CLI.

**Comment by zelch** [comment]
This isn't a gimme-aws-creds bug, this is an Okta bug.

If you have Okta setup to require the external IdP before granting access, the API gimme-aws-creds is using should not be capable of getting working AWS credentials without going through a similar path.

You need to raise this issue with Okta, as a security issue, and figure out what is misconfigured.

Now, it is possible that gimme-aws-creds will break once the issue is fixed, and from my memory of the API, I'm not sure that the API has any mechanism to list a MFA factor for an external IdP, but the bigger issue is that the API simply shouldn't _work_ in your configuration without that external MFA step.

And there is nothing that gimme-aws-creds can do to fix that security hole.

**Comment by epierce** [comment]
gimme-aws-creds uses the [Authentication API](https://developer.okta.com/docs/reference/api/authn/), so it can't be used with a federated IdP. If we add browser-based authentication in the future (this might be necessary for Okta Identity Engine support), the federated auth should work.
