### ISSUE TITLE
Parsing broken on new AWS SAML login page if resolve_aws_alias true

### ISSUE THREAD

**Issue by markjreed** [Nike-Inc/gimme-aws-creds#425]
## Expected Behavior
gimme-aws-creds should see all of my assigned roles and prompt 

## Current Behavior
gimme-aws-creds sees only a single role (first one on page)

## Possible Solution
Need to adjust parsing of SAML login page HTML

## Steps to Reproduce (for bugs)
1. Get more than one role assigned in AWS via SAML provider
2. Run gimme-aws-creds without any arguments to select a role

## Context

Lots of IaC with hard-coded AWS_PROFILE values that include account aliases, now must be changed to account-id (or workflow changed to specify profile names)

## Your Environment

* App Version used:
* 2.7.1

* Operating System and version:
macOS 13.4.1

**Comment by SteveyPugs** [comment]
Seeing the same. Now sees it as a single login.

**Comment by chrissnell-okta** [comment]
It appears that AWS changed the design of the role selection page in the login workflow.  Guessing that gimme-aws-creds will have to be updated to scrape the role names from this new design.

**Comment by drwelby** [comment]
I was hoping a quick regex update in the scraping would fix it but the new page returned is some NextJS mess...

**Comment by jpenagg** [comment]
looks like AWS might have just reverted the change?

**Comment by patrickleet** [comment]
> looks like AWS might have just reverted the change?

I saw that, and was gonna say something, but then I refreshed and new design was back again - maybe it's some sort of canary percentage based roll-out?

**Comment by drwelby** [comment]
Seems to be consistently back to vanilla html.

I stashed a response and have what I think could be the basis of a fix:

[aws.py.diff.txt](https://github.com/Nike-Inc/gimme-aws-creds/files/12399522/aws.py.diff.txt)

**Comment by drwelby** [comment]
Summing it all up:

- AWS "upgraded" the account page to a NextJS page that does search and pagination and other pretty stuff before rolling it back
- Since the page is rendered client side, there no longer were account IDs in the HTML to scrape
- Solution (above) is to find the base64'ed JSON data payload in the NextJS page, decode it, then parse out the account IDs

**Comment by joepurdy** [comment]
We were impacted by this change since we have a wrapper utility (https://github.com/ArcadiaPower/axolotl) that depends on gimme-aws-creds for performing the SAML login to obtain credentials. I also managed to snag the response of the new NextJS page this morning prior to AWS reverting and worked out a fix that parses the same values from the new JSON metadata.

Unless I hear differently I'll get a PR drafted for when/if AWS moves forward with the switch to the new login page.
