### ISSUE TITLE
MFA issue 

### ISSUE THREAD

**Issue by satssin** [Nike-Inc/gimme-aws-creds#52]
Hi Team,
I have user  he got MFA setup for this account in OKTA, however when he run gimme-aws-creds command to generate credentials it doesn't ask for MFA and after  selecting the AWS roles it just through this exception
![screen shot 2018-04-19 at 4 28 40 pm](https://user-images.githubusercontent.com/4459386/39016547-bf9a4dfa-43ee-11e8-8d6c-1c0422116247.png)

**Comment by epierce** [comment]
My guess on the first issue would be that there's an issue with the sign-on policy in Okta.  Does the user get prompted for MFA when they access the AWS console with a browser?  

The error message you're seeing is because you've got an invalid region in your AWS configuration (`~/.aws/config`).  From the URL in the error message, you have the default region set to `us-east` instead of `us-east-1` or `us-east-2`

**Comment by satssin** [comment]
Thank you, Eric , we figured it out, it was the problem with the ~/.aws/config file.





Satish Kumar|Manager, DevOps Solutions | GTS|MCSE,RHCA,ITIL,OCWA,SCSA,AWS,CCNA
Email:satish.kumar1@mheducation.com|Cell:9732896721
-
