### ISSUE TITLE
unable to pipe output because questions are printed to stdout

### ISSUE THREAD

**Issue by tyrsius** [Nike-Inc/gimme-aws-creds#67]
So there is an option to write to your disk, but I would rather these creds be as ephemeral as possible. The tool is already nice enough to print them with `export` so that you can copy/paste them, but it would be _even easier_ if we could

```
gimme-aws-creds | sh
```

And have it work. The issue is that currently the questions are printed to `stdout`, which screws with the pipe. If they were printed to `stderr` instead, the above command would work.

**Comment by Sector95** [comment]
Really good idea!  Shouldn't be too tough of a change, either.

**Comment by epierce** [comment]
I looked at this a little bit last night - the `export` statements are being printed to stderr right now, so you can do this `source <(gimme-aws-creds 2>&1 >/dev/null)` That redirects stderr to stdout and the original stdout to /dev/null.

However, that hides stdout completely, so it only works if you don't need to answer any prompts.  Moving all user interaction to stderr and the `export` output to stdout is a good solution - that should let users select which account/role they want or input their MFA code and still be able to pass the output to the shell.

**Comment by sperry04** [comment]
I believe I was the one that added the export output mode.  I used stderr simply because all the rest of the logging already on stdout and I wanted to be able to redirect the exports to a file, as mentioned above.  

If you create a profile for the target accounts you use, you can get GAC to work without user input, with the exception of the MFA prompt.  However if we merge PR #65, I've added the ability to pass MFA creds in as a CLI param.

The way I use this is with an `awscreds.sh` bash script similar to this:

`gimme-aws-creds -u scott.perry@nike.com --mfa-code "$(getMFA)" -p "$1" 2>/tmp/aws_creds_vars;`

`getMFA` is a function that gets a current MFA code from oathtool, `$1` is the name of the account profile to get creds for (I've setup profiles for all the accounts I regularly use).  This bash script gets called by a function I have defined in my `.bashrc`:

`function awscreds { if awscreds.sh "$1"; then source /tmp/aws_creds_vars; fi; }`

Because exported env vars only apply to the forked shell they're defined in, you need the function alias defined in your _current_ shell to source the output of the tool (as in epierce's example above).  This function and script, working together, allows me to simply type something like `awscreds test` and my current shell is loaded with the proper env vars, even with MFA enabled.

**Comment by tyrsius** [comment]
@sperry04 That's a pretty good workaround. If that mfa-code PR gets merged I will use that in the meantime. I still think it would be really nice to get the pipe to bash working, since it simplifies the call and removes the write to `/tmp`

**Comment by sperry04** [comment]
Keep in mind that piping to `sh` isn't going to put the credential env vars into your current shell, it's going to put them into the shell forked by the `sh` call you piped to, which will go away as soon as the command ends.  The only way to get the env vars into your current shell is to `source` them in your current shell, like in epierce's example, or in the function in my example.  That is, unless I'm missing a bash trick I'm not aware of.

**Comment by tyrsius** [comment]
They should still appear if I follow the command

```
gimme-aws-creds | sh && something-requiring-creds
```

right?

**Comment by sperry04** [comment]
Your first example doesn't work, I don't think.  Here's a simplified example:

`echo "export TESTVAR=value" | sh && env`

The export is executed by `sh`, but then that shell exits (returning 0) and then the `env` command executes.

A perhaps better way to do what you're trying would not be to use `export`, but something like this:

`TESTVAR=value env` or `export TESTVAR=value; env`

where the env value(s) are specified inline prior to the command that will use them, or as part of a multiple command script.  Your second example is the `source` equivalent to that, I think, with the side-effect that after the command is executed, your current shell continues to have the assigned credential vars.

I guess it depends on the use case.  If you intend to always run a single command with new credentials that exist only for the life of the command, the `source` based methods won't do that cleanly.  But, at least in my use case, I need to give my current shell AWS credential env vars so that I can run a bunch of ad-hoc aws CLI commands, which is well served by `source`ing the exports into my current shell.

**Comment by tyrsius** [comment]
Ah, good to know. The `source $(gimme-aws-creds --mfa-code=243)` option is still pretty good then.
